version: "3"

services:
  verlihub:
#    build: ./build
    image: verlihub:1.4.0
    container_name: verlihub
    environment:
      - VH_UID=1000
#      - DO_NOT_LINK_PLUGINS=1
    depends_on: 
      - verlihub-db
    ulimits:
      core:
        hard: 0
        soft: 0
    volumes:
      - ./verlihub:/etc/verlihub
      - ./GeoIP:/usr/share/GeoIP
    ports:
      - "4111:4111"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 128M
    restart: unless-stopped

  verlihub-db:
    image:  yobasystems/alpine-mariadb:latest
    container_name: verlihub-db
    env_file:
      - ./db.env
    volumes:
    - "./mysql:/var/lib/mysql"
#    - "./verlihub.sql:/verlihub.sql"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
    restart: unless-stopped
